config/routes.rb
GMapRS::Application.routes.draw do
  
  resources :map_places

  match 'home/index', to: 'home#index', via: [:get]
  match 'home/map_place_create', to: 'home#map_place_create', via: [:post]

  root 'home#index'

  

end

app/models/map_place.rb
class MapPlace < ActiveRecord::Base
  validates :place, presence: true, uniqueness: true
  validates :latitude, presence: true, uniqueness: true
  validates :longitude, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @map_place = MapPlace.new
  end 
  
  def map_place_create
    @map_place = MapPlace.new(map_place_params)
    
    respond_to do |format|
      if @map_place.save
        format.js { render :layout => false } 
      else
        format.js { render :layout => false }
      end
    end
  end
  
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def map_place_params
      params.require(:map_place).permit(:place, :latitude, :longitude)
    end
end

app/controllers/map_places_controller.rb
class MapPlacesController < ApplicationController
  before_action :set_map_place, only: [:show, :edit, :update, :destroy]

  # GET /map_places
  # GET /map_places.json
  def index
    @map_places = MapPlace.all
  end

  # GET /map_places/1
  # GET /map_places/1.json
  def show
  end

  # GET /map_places/new
  def new
    @map_place = MapPlace.new
  end

  # GET /map_places/1/edit
  def edit
  end

  # POST /map_places
  # POST /map_places.json
  def create
    @map_place = MapPlace.new(map_place_params)

    respond_to do |format|
      if @map_place.save
        format.html { redirect_to @map_place, notice: 'Map place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @map_place }
      else
        format.html { render action: 'new' }
        format.json { render json: @map_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /map_places/1
  # PATCH/PUT /map_places/1.json
  def update
    respond_to do |format|
      if @map_place.update(map_place_params)
        format.html { redirect_to @map_place, notice: 'Map place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @map_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /map_places/1
  # DELETE /map_places/1.json
  def destroy
    @map_place.destroy
    respond_to do |format|
      format.html { redirect_to map_places_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map_place
      @map_place = MapPlace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_place_params
      params.require(:map_place).permit(:place, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_places_helper.rb
module MapPlacesHelper
end

app/views/home/_create_success.html.erb
<% unless @map_place.errors.size > 0 %>
	<div class="alert alert-success">
		<span class="label label-default">Place Title:</span>
		<span><%= @map_place.place %></span>
		
	  <span class="label label-default">Latitude:</span> 
	  <span><%= @map_place.latitude %></span>
		
		<span class="label label-default">Longitude:</span> 
		<span><%= @map_place.longitude %></span>
		
		Map place was successfully created.
	</div>
<% else %>
	<div class="alert alert-danger">
		<%= @map_place.errors.messages %>
	</div>
<% end %>

app/views/home/index.html.erb
<% mplaces = MapPlace.all %>
<% 
	places = []
	mplaces.each do |p|
		places << [p.place, p.latitude.to_f, p.longitude.to_f]	
	end
%>


<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBy4XcgWoZ8HAxervtJV9EPhrWRBEtrTKY&sensor=false"></script>
<script>
	function initialize()
	{
		var mapProp = {
		  center:new google.maps.LatLng(15.92039413902405,102.579345703125),
		  zoom:4,
		  mapTypeId:google.maps.MapTypeId.ROADMAP
		  };
		var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
		
		google.maps.event.addListener(map,'click',function(event){ 
			document.getElementById('map_place_latitude').value = event.latLng.lat();
			document.getElementById('map_place_longitude').value = event.latLng.lng(); 
		});
		
		google.maps.event.addListener(map,'mousemove',function(event) { 
			document.getElementById('latspan').innerHTML = event.latLng.lat() 
			document.getElementById('lngspan').innerHTML = event.latLng.lng() 
			document.getElementById('latlong').innerHTML = event.latLng.lat() + ', ' + event.latLng.lng() 
		});	 
		
		setMarkers(map, places);
	}
	
	var places = <%= raw places.to_json %>;
	
	function setMarkers(map, locations) {
	  for (var i = 0; i < locations.length; i++) {
	    var beach = locations[i];
	    var myLatLng = new google.maps.LatLng(beach[1], beach[2]);
	    var marker = new google.maps.Marker({
	        position: myLatLng,
	        map: map,
	        title: beach[0]
	    });
	  }
	}
	
	google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div id="googleMap" style="width:100%;height:380px;"></div>

<div class="clearfix">&nbsp;</div>

<div class="alert alert-info">
  <span class="label label-default">Latitude:</span> 
  <span id="latspan"></span><br/>
	
	<span class="label label-default">Longitude:</span> 
	<span id="lngspan"></span><br/>
	
	<span class="label label-default">Lat Lng:</span>
	<span id="latlong"></span>
</div>

<div id="map_place_after_save"></div>

<div class="row">
	<div class="col-md-12">
		<%= form_for(@map_place, url: home_map_place_create_path, html: {remote: true, class: 'form-horizontal', role: 'form'}) do |f| %>
			<div class="form-group">
			  <label for="map_place_place" class="col-sm-2 control-label">Place Title</label>
			  <div class="col-sm-5">
			    <%= text_field :map_place, :place, class: "form-control" %>
			  </div>
			</div>
			
			<div class="form-group">
			  <label for="map_place_latitude" class="col-sm-2 control-label">Latitude</label>
			  <div class="col-sm-5">
			    <%= text_field :map_place, :latitude, class: "form-control" %>
			  </div>
			</div>
			
			<div class="form-group">
			  <label for="map_place_longitude" class="col-sm-2 control-label">Longitude</label>
			  <div class="col-sm-5">
			    <%= text_field :map_place, :longitude, class: "form-control" %>
			  </div>
			</div>
			
			<div class="clearfix form-actions">
				<div class="col-md-offset-3 col-md-9">
	      	<%= f.button :button, class: 'btn btn-primary' do %>
	        	<i class="icon-ok bigger-110"></i>
	        	<%= t'.submit'%>
	      	<% end %>
				</div>
			</div>
		<% end %>
		<div class="clearfix">&nbsp;</div>
  </div>
</div>

app/views/home/map_place_create.js.erb
$("#map_place_after_save").html("<%=j render(partial: "create_success") %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GMapRS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  
  <link href="/bootstraptemplate-3.1.1/css/bootstrap.min.css" rel="stylesheet">
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="navbar" class="navbar navbar-default blue">
		<div id="navbar-container" class="navbar-container">
			<div class="navbar-header pull-left">
				<a class="navbar-brand" href="/home/index">
					<small>
						<i class="icon-leaf"></i>
						Google Map Marker
					</small>
				</a>
			</div>
			 <!-- Collect the nav links, forms, and other content for toggling -->
    	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="/map_places">Map Place</a></li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
			
		</div>
	</div>
	
	<div class="container">
		<%= yield %>
	</div>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="/bootstraptemplate-3.1.1/js/bootstrap.min.js"></script>
</body>
</html>

app/views/map_places/_form.html.erb
<%= form_for(@map_place) do |f| %>
  <% if @map_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map_place.errors.count, "error") %> prohibited this map_place from being saved:</h2>

      <ul>
      <% @map_place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/map_places/edit.html.erb
<h1>Editing map_place</h1>

<%= render 'form' %>

<%= link_to 'Show', @map_place %> |
<%= link_to 'Back', map_places_path %>

app/views/map_places/index.html.erb
<h1>Listing map_places</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @map_places.each do |map_place| %>
      <tr>
        <td><%= map_place.place %></td>
        <td><%= map_place.latitude %></td>
        <td><%= map_place.longitude %></td>
        <td><%= link_to 'Show', map_place %></td>
        <td><%= link_to 'Edit', edit_map_place_path(map_place) %></td>
        <td><%= link_to 'Destroy', map_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map place', new_map_place_path %>

app/views/map_places/new.html.erb
<h1>New map_place</h1>

<%= render 'form' %>

<%= link_to 'Back', map_places_path %>

app/views/map_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place:</strong>
  <%= @map_place.place %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @map_place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @map_place.longitude %>
</p>

<%= link_to 'Edit', edit_map_place_path(@map_place) %> |
<%= link_to 'Back', map_places_path %>